- .gitattributes
- pom.xml
- src/main/java/com/artpie/nuget/Nuspec.java
- src/main/java/com/artpie/nuget/PackageIdentity.java
- src/main/java/com/artpie/nuget/Repository.java
- src/test/java/com/artpie/nuget/NewtonJsonPackage.java
- src/test/java/com/artpie/nuget/NewtonJsonResource.java
- src/test/java/com/artpie/nuget/NuspecTest.java
- src/test/resources-binary/newtonsoft.json/12.0.3/newtonsoft.json.nuspec
This is part of issue: https://github.com/artipie/nuget-adapter/issues/1
Adding package to repository includes saving .nuspec manifest extracted from package to package path.
> #1 - Nuspec parsing & saving

- .github/workflows/git.yaml
- .github/workflows/maven.yml
Added `pull_request` event to trigger
> Gixed actions build

- src/main/java/com/artpie/nuget/Versions.java
- src/test/java/com/artpie/nuget/VersionsTest.java
Issue: #22 
Added Versions class to represent package versions enumeration. Versions are going to be stored in ASTO storage
> #22 - Added Versions class to represent package versions enumeration

- pom.xml
- src/main/java/com/artpie/nuget/Version.java
- src/test/java/com/artpie/nuget/VersionTest.java
Issue #23 
Proper implementation of version normalization
> #23 - Version.normalized() implementation

- pom.xml
- src/main/java/com/artpie/nuget/Repository.java
- src/main/java/com/artpie/nuget/Versions.java
- src/test/java/com/artpie/nuget/RepositoryTest.java
- src/test/java/com/artpie/nuget/VersionsTest.java
Issue #22 
Added Repository.versions() method to get package versions enumeration.
> #22 - Added Repository.versions() method to get all versions of package

- src/main/java/com/artpie/nuget/Versions.java
- src/test/java/com/artpie/nuget/VersionsTest.java
Part of issue #22 
Adds method `Version.add()` to add versions package. The method is going to be used on adding new package to repository.
> #22 - Added Versions.add() method

- pom.xml
- src/main/java/com/artpie/nuget/Repository.java
- src/test/java/com/artpie/nuget/RepositoryIT.java
- src/test/java/com/artpie/nuget/RepositoryTest.java
- src/test/resources/log4j.properties
Closes issue #22 
Version is added to versions registry on add to repository, integration test for listing versions
> #22 - Updating versions list when package is added

- README.md
> #35 - Project status section added to README.md

- pom.xml
> #38 - Updated parent to 0.3 and ASTO to 0.14.1

- src/main/java/com/artpie/nuget/http/NuGet.java
- src/main/java/com/artpie/nuget/http/PackageContent.java
- src/main/java/com/artpie/nuget/http/Root.java
- src/test/java/com/artpie/nuget/http/NuGetTest.java
Part of issue #20 
Adds routing to Root resource where put method should be implemented later
> #20 - Support for root resource routing

- .github/workflows/maven.yml
- pom.xml
- src/main/java/com/artpie/nuget/http/NuGet.java
- src/main/java/com/artpie/nuget/http/PackageContent.java
- src/main/java/com/artpie/nuget/http/Root.java
- src/test/java/com/artpie/nuget/http/NuGetTest.java
Closes issue #45 
Migration to HTTP 0.5
> #45 - Migrated to HTTP 0.5

- pom.xml
- src/test/java/com/artpie/nuget/HashTest.java
- src/test/java/com/artpie/nuget/NupkgTest.java
- src/test/java/com/artpie/nuget/NuspecTest.java
- src/test/java/com/artpie/nuget/RepositoryTest.java
Closes issue #43 
Replaced FileStorage with InMemoryStorage in tests
> #43 - Using InMemoryStorage in tests instead of FileStorage in tests

- pom.xml
- src/main/java/com/artpie/nuget/http/NuGet.java
- src/main/java/com/artpie/nuget/http/PackageContent.java
- src/test/java/com/artpie/nuget/http/NuGetTest.java
Implementation for GET method of PackageContent resource. Serves data from storage by key, returns 404 in case value does not exist
> #19 - Support for GET method of PackageContent resource

- pom.xml
- src/main/java/com/artpie/nuget/http/NuGet.java
- src/main/java/com/artpie/nuget/http/PackageContent.java
- src/main/java/com/artpie/nuget/http/Resource.java
- src/main/java/com/artpie/nuget/http/Root.java
- src/test/java/com/artpie/nuget/http/NuGetTest.java
Part of issue #20 
Handles uploading package via HTTP PUT request when package bytes are passed in body as-is.
> #20 - Uploading package by PUT request to root resource

- src/main/java/com/artpie/nuget/http/Root.java
- src/test/java/com/artpie/nuget/http/NuGetTest.java
Part of #20 
Adding package to Repository when it is pushed via HTTP
> #20 - Adding a package via HTTP

- src/main/java/com/artpie/nuget/http/Absent.java
- src/main/java/com/artpie/nuget/http/NuGet.java
- src/main/java/com/artpie/nuget/http/PackageContent.java
- src/main/java/com/artpie/nuget/http/PackagePublish.java
- src/main/java/com/artpie/nuget/http/Route.java
- src/main/java/com/artpie/nuget/http/RoutingResource.java
- src/test/java/com/artpie/nuget/http/NuGetTest.java
Part of #19 
Changed resources scheme of NuGet repository and prepared for adding more resources to fully support NuGet install command (ServiceIndex, PackageMetadata)
> #19 - Routing changes and refactoring in NuGet

- pom.xml
- src/test/java/com/artpie/nuget/RepositoryHttpIT.java
Added integration test to check that install works with HTTP NuGet repository. Disabled now, when the test is passing then issue #19 may be closed
> #19 - NuGet install integration tests

- src/main/java/com/artpie/nuget/http/NuGet.java
- src/main/java/com/artpie/nuget/http/ServiceIndex.java
- src/test/java/com/artpie/nuget/http/NuGetServiceIndexTest.java
Added ServiceIndex route to server service index later.
> #19 - Service index routing

- src/main/java/com/artpie/nuget/http/NuGet.java
- src/main/java/com/artpie/nuget/http/RouteService.java
- src/main/java/com/artpie/nuget/http/Service.java
- src/main/java/com/artpie/nuget/http/ServiceIndex.java
- src/test/java/com/artpie/nuget/RepositoryHttpIT.java
- src/test/java/com/artpie/nuget/http/NuGetServiceIndexTest.java
- src/test/java/com/artpie/nuget/http/NuGetTest.java
Added Service interface to represent services that could present in service index. Added PackagePublish and PackageContent services
> #19 - Added actual services to service index response

- src/main/java/com/artpie/nuget/Version.java
- src/test/java/com/artpie/nuget/VersionTest.java
Package metadata service of NuGet repository should give list of known versions in order. This PR making `Version` comparable, so package versions list may be properly ordered
> #19 - Comparable Version

- src/main/java/com/artpie/nuget/NuGetPackage.java
- src/main/java/com/artpie/nuget/Nupkg.java
- src/main/java/com/artpie/nuget/Repository.java
- src/test/java/com/artpie/nuget/NupkgTest.java
- src/test/java/com/artpie/nuget/RepositoryTest.java
Closes issue #21 
When package is added it is moved to proper location instead of copying.
> #21 - Moving new package when it is added to repository

- src/main/java/com/artpie/nuget/http/NuGet.java
- src/main/java/com/artpie/nuget/http/metadata/PackageMetadata.java
- src/main/java/com/artpie/nuget/http/metadata/Pages.java
- src/main/java/com/artpie/nuget/http/metadata/Registration.java
- src/main/java/com/artpie/nuget/http/metadata/package-info.java
- src/test/java/com/artpie/nuget/http/metadata/NuGetPackageMetadataTest.java
- src/test/java/com/artpie/nuget/http/metadata/package-info.java
Part of issue #19
Added package metadata service route
> #19 - Added package metadata route

- src/main/java/com/artpie/nuget/http/NuGet.java
- src/test/java/com/artpie/nuget/http/NuGetServiceIndexTest.java
Part of #19 
Added PackageMetadata to service index & NuGetServiceIndexTest refactoring
> #19 - Added PackageMetadata to service index

- src/main/java/com/artpie/nuget/http/NuGet.java
- src/main/java/com/artpie/nuget/http/metadata/PackageMetadata.java
- src/main/java/com/artpie/nuget/http/metadata/Registration.java
- src/test/java/com/artpie/nuget/http/metadata/NuGetPackageMetadataTest.java
Part of #19 
Registration service outputs versions in pages, always one page for now for simplicity
> #19 - Generating version pages in Registration

- src/main/java/com/artpie/nuget/PackageId.java
- src/main/java/com/artpie/nuget/http/metadata/Registration.java
- src/main/java/com/artpie/nuget/http/metadata/RegistrationPage.java
- src/test/java/com/artpie/nuget/PackageIdTest.java
- src/test/java/com/artpie/nuget/http/metadata/NuGetPackageMetadataTest.java
- src/test/java/com/artpie/nuget/http/metadata/RegistrationPageTest.java
Part of #19
Added registration leaf objects to registration pages
> #19 - Populating registration leaves with metadata

- src/main/java/com/artpie/nuget/http/NuGet.java
- src/main/java/com/artpie/nuget/http/PackageContent.java
- src/main/java/com/artpie/nuget/http/metadata/ContentLocation.java
- src/main/java/com/artpie/nuget/http/metadata/ContentStorage.java
- src/main/java/com/artpie/nuget/http/metadata/PackageMetadata.java
- src/main/java/com/artpie/nuget/http/metadata/Registration.java
- src/main/java/com/artpie/nuget/http/metadata/RegistrationPage.java
- src/test/java/com/artpie/nuget/http/metadata/RegistrationPageTest.java
Part of #19 
Added `packageContent` URL to registration leaf
> #19 - Added package content location to registration leaves

- README.md
- src/test/java/com/artpie/nuget/RepositoryHttpIT.java
Closes #19 
Enabled test for installation package via HTTP, project status updated
> #19 - Package installation finalized

- README.md
Closes #52 
Added notes regarding integration tests run to README.md
> #52 - Added notes regarding integration tests run to README.md

- pom.xml
- src/main/java/com/artpie/nuget/http/Absent.java
- src/main/java/com/artpie/nuget/http/Headers.java
- src/main/java/com/artpie/nuget/http/NuGet.java
- src/main/java/com/artpie/nuget/http/PackageContent.java
- src/main/java/com/artpie/nuget/http/PackagePublish.java
- src/main/java/com/artpie/nuget/http/Resource.java
- src/main/java/com/artpie/nuget/http/RoutingResource.java
- src/main/java/com/artpie/nuget/http/ServiceIndex.java
- src/main/java/com/artpie/nuget/http/metadata/Registration.java
- src/test/java/com/artpie/nuget/http/NuGetTest.java
Part of #20 
Push package body request accepted in multipart format
> #20 - Multipart body support for package push

- README.md
- pom.xml
- src/test/java/com/artpie/nuget/RepositoryHttpIT.java
- src/test/resources/log4j.properties
Closes #20 
Added integration test for NuGet push operation and updated project status in README.md
> #20 - Finalized push package via HTTP

- .github/workflows/maven.yml
Closes #80
Added back NuGet client setup step to maven.yml
> #80 - Added back NuGet client setup step to maven.yml

- .github/workflows/codecov.yml
- pom.xml
> #82 - Enabled code coverage reports, upgraded ppom to 0.3.3

- src/test/java/com/artipie/nuget/RepositoryHttpIT.java
Part of #84 
Enabled basic authentication in integration tests
> #84 - Authentication in integration tests

- src/main/java/com/artipie/nuget/http/Absent.java
- src/main/java/com/artipie/nuget/http/NuGet.java
- src/main/java/com/artipie/nuget/http/Resource.java
- src/main/java/com/artipie/nuget/http/RoutingResource.java
- src/main/java/com/artipie/nuget/http/content/PackageContent.java
- src/main/java/com/artipie/nuget/http/index/ServiceIndex.java
- src/main/java/com/artipie/nuget/http/metadata/Registration.java
- src/main/java/com/artipie/nuget/http/publish/PackagePublish.java
Part of #84 
Added headers parameter, as they will be required for request authentication.
> #84 - Added headers to Reosurce.get method

- src/main/java/com/artipie/nuget/http/SliceFromResource.java
- src/test/java/com/artipie/nuget/http/SliceFromResourceTest.java
Part of #84
Added `SliceFromResource` class required for interoperation between `AuthSlice` class from HTTP module and `Resource` classes in NuGet repository
> #84 - Added SliceFromResource

- pom.xml
- src/main/java/com/artipie/nuget/http/BasicAuthRoute.java
- src/main/java/com/artipie/nuget/http/NuGet.java
- src/test/java/com/artipie/nuget/http/content/NuGetPackageContentTest.java
Part of #84 
Basic authentication support added for package content reading
> #84 - Basic auth support for reading content

- src/main/java/com/artipie/nuget/http/NuGet.java
- src/test/java/com/artipie/nuget/RepositoryHttpIT.java
- src/test/java/com/artipie/nuget/http/TestAuthentication.java
- src/test/java/com/artipie/nuget/http/metadata/NuGetPackageMetadataTest.java
Closes #84 
Auth support in metadata service, auth enabled in integration tests
> #84 - Auth support finished

- pom.xml
- src/main/java/com/artipie/nuget/Hash.java
- src/main/java/com/artipie/nuget/Nuspec.java
- src/main/java/com/artipie/nuget/Repository.java
- src/main/java/com/artipie/nuget/Versions.java
- src/main/java/com/artipie/nuget/http/metadata/Registration.java
- src/main/java/com/artipie/nuget/http/metadata/RegistrationPage.java
- src/main/java/com/artipie/nuget/http/publish/PackagePublish.java
- src/test/java/com/artipie/nuget/HashTest.java
- src/test/java/com/artipie/nuget/RepositoryIT.java
- src/test/java/com/artipie/nuget/RepositoryTest.java
- src/test/java/com/artipie/nuget/VersionsTest.java
- src/test/java/com/artipie/nuget/http/content/NuGetPackageContentTest.java
> #94 - ASTO update to 0.23.2

- src/main/java/com/artipie/nuget/http/ResourceFromSlice.java
- src/test/java/com/artipie/nuget/http/ResourceFromSliceTest.java
- src/test/java/com/artipie/nuget/http/SliceFromResourceTest.java
- src/test/java/com/artipie/nuget/http/TestAuthentication.java
- src/test/java/com/artipie/nuget/http/content/NuGetPackageContentTest.java
- src/test/java/com/artipie/nuget/http/index/NuGetServiceIndexTest.java
- src/test/java/com/artipie/nuget/http/metadata/NuGetPackageMetadataTest.java
- src/test/java/com/artipie/nuget/http/publish/NuGetPackagePublishTest.java
Closes #94
Added usage of new features of HTTP 0.15
> #94 - Added usage of recent features from HTTP

- src/main/java/com/artipie/nuget/http/NuGet.java
- src/test/java/com/artipie/nuget/RepositoryHttpIT.java
- src/test/java/com/artipie/nuget/http/content/NuGetPackageContentTest.java
- src/test/java/com/artipie/nuget/http/index/NuGetServiceIndexTest.java
- src/test/java/com/artipie/nuget/http/metadata/NuGetPackageMetadataTest.java
- src/test/java/com/artipie/nuget/http/publish/NuGetPackagePublishTest.java
Closes #98 
Base path feature removed
> #98 - Base path feature removed

- src/main/java/com/artipie/nuget/Nuspec.java
- src/test/java/com/artipie/nuget/NuspecTest.java
> Make code xml schema-independent

- src/main/java/com/artipie/nuget/PackageId.java
- src/main/java/com/artipie/nuget/PackageIdentity.java
- src/main/java/com/artipie/nuget/Repository.java
- src/test/java/com/artipie/nuget/PackageIdTest.java
- src/test/java/com/artipie/nuget/RepositoryTest.java
Part of #113
Repository.add access storage exclusively to avoid race conditions
> #113 - Repository.add access storage exclusively

- pom.xml
- src/main/java/com/artipie/nuget/http/NuGet.java
- src/test/java/com/artipie/nuget/http/TestPermissions.java
- src/test/java/com/artipie/nuget/http/content/NuGetPackageContentTest.java
- src/test/java/com/artipie/nuget/http/metadata/NuGetPackageMetadataTest.java
- src/test/java/com/artipie/nuget/http/publish/NuGetPackagePublishTest.java
> #1 - Bumped HTTP dependency

- src/main/java/com/artipie/nuget/Hash.java
- src/main/java/com/artipie/nuget/NuGetPackage.java
- src/main/java/com/artipie/nuget/Nupkg.java
- src/main/java/com/artipie/nuget/Repository.java
- src/test/java/com/artipie/nuget/HashTest.java
- src/test/java/com/artipie/nuget/NupkgTest.java
Part of #117 
`Nupkg` and `Hash` classes changed to be async
> #117 - Nupkg and Hash classes changed to be async

- src/main/java/com/artipie/nuget/Nuspec.java
- src/main/java/com/artipie/nuget/Repository.java
- src/main/java/com/artipie/nuget/Versions.java
- src/main/java/com/artipie/nuget/http/metadata/Registration.java
- src/main/java/com/artipie/nuget/http/metadata/RegistrationPage.java
- src/main/java/com/artipie/nuget/http/publish/PackagePublish.java
- src/test/java/com/artipie/nuget/NuspecTest.java
- src/test/java/com/artipie/nuget/RepositoryTest.java
- src/test/java/com/artipie/nuget/VersionsTest.java
- src/test/java/com/artipie/nuget/http/metadata/NuGetPackageMetadataTest.java
Part of #117 
`Nuspec` and `Versions` classes changed to be async
> #117 - Nuspec and Versions class changed to be async

- src/main/java/com/artipie/nuget/Repository.java
- src/main/java/com/artipie/nuget/http/metadata/Registration.java
- src/main/java/com/artipie/nuget/http/metadata/RegistrationPage.java
- src/test/java/com/artipie/nuget/RepositoryTest.java
- src/test/java/com/artipie/nuget/http/metadata/RegistrationPageTest.java
Part of #117 
`Repository.nuspec` made async
> #117 - Repository.nuspec made async

- src/main/java/com/artipie/nuget/InvalidPackageException.java
- src/main/java/com/artipie/nuget/PackageVersionAlreadyExistsException.java
- src/main/java/com/artipie/nuget/Repository.java
- src/main/java/com/artipie/nuget/http/publish/PackagePublish.java
- src/test/java/com/artipie/nuget/RepositoryIT.java
- src/test/java/com/artipie/nuget/RepositoryTest.java
Closes #117 
`Repository` made async
> #117 - Repository made async

- src/main/java/com/artipie/nuget/Repository.java
- src/main/java/com/artipie/nuget/http/NuGet.java
- src/main/java/com/artipie/nuget/http/publish/PackagePublish.java
- src/test/java/com/artipie/nuget/NewtonJsonResource.java
- src/test/java/com/artipie/nuget/RepositoryIT.java
- src/test/java/com/artipie/nuget/RepositoryTest.java
Part of #124 
`PackagePublish` does not interact with `Storage` directly
> #124 - PackagePublish does not interact with Storage directly

- src/main/java/com/artipie/nuget/Repository.java
- src/main/java/com/artipie/nuget/http/NuGet.java
- src/main/java/com/artipie/nuget/http/content/PackageContent.java
- src/test/java/com/artipie/nuget/RepositoryHttpIT.java
- src/test/java/com/artipie/nuget/http/content/NuGetPackageContentTest.java
- src/test/java/com/artipie/nuget/http/index/NuGetServiceIndexTest.java
- src/test/java/com/artipie/nuget/http/metadata/NuGetPackageMetadataTest.java
- src/test/java/com/artipie/nuget/http/publish/NuGetPackagePublishTest.java
Closes #124 
NuGet does not interact with Storage directly
> #124 - NuGet does not interact with Storage directly

- src/main/java/com/artipie/nuget/AstoRepository.java
- src/main/java/com/artipie/nuget/Repository.java
- src/test/java/com/artipie/nuget/AstoRepositoryIT.java
- src/test/java/com/artipie/nuget/AstoRepositoryTest.java
- src/test/java/com/artipie/nuget/RepositoryHttpIT.java
- src/test/java/com/artipie/nuget/http/content/NuGetPackageContentTest.java
- src/test/java/com/artipie/nuget/http/index/NuGetServiceIndexTest.java
- src/test/java/com/artipie/nuget/http/metadata/NuGetPackageMetadataTest.java
- src/test/java/com/artipie/nuget/http/metadata/RegistrationPageTest.java
- src/test/java/com/artipie/nuget/http/publish/NuGetPackagePublishTest.java
Closes #123 
Repository interface extracted
> #123 - Repository interface extracted

- pom.xml
- src/main/java/com/artipie/nuget/InvalidPackageException.java
- src/main/java/com/artipie/nuget/PackageVersionAlreadyExistsException.java
- src/main/java/com/artipie/nuget/http/BasicAuthRoute.java
- src/main/java/com/artipie/nuget/http/NuGet.java
- src/test/java/com/artipie/nuget/AstoRepositoryTest.java
- src/test/java/com/artipie/nuget/RepositoryHttpIT.java
- src/test/java/com/artipie/nuget/http/TestPermissions.java
Updated asto and http, used `ArtipieException`
> Update asto http
